config/routes.rb
Rails.application.routes.draw do

  # resources :flats
  # devise_for :users, :paths => 'users'
  # resource :user do
  #   resources :flats
  # end
  get 'flats/owned', to: 'flats#owned', as: :owned_flats
  get 'flats/booked', to: 'flats#booked', as: :booked_flats
  devise_for :users
  resources :flats do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reservations

  root to: 'pages#home'
  # resources :flats


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :reservations
  has_many :reviews

  validates :price, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :address, presence: true


  has_many_attached :photos

  def get_country
    address.match(/\s(\w+)$/)[0]
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :status, inclusion: { in: ["pending", "approved", "rejected"]}
  validates :reservation_start, :reservation_end, presence: true

  belongs_to :flat
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
validates :rating, :inclusion => 1..5
  belongs_to :flat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :owned_flats, foreign_key: "user_id" , class_name: "Flat"

  has_many :reservations

  has_many :booked_flats, source: :flat, through: :reservations

  validates :username, uniqueness: true

  has_one_attached :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
     # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :avatar, :description])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :avatar, :description])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only:[:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # @flats = Flat.all
    # return @flats = policy_scope(Flat).where(location: params[:location].capitalize) if params[:location]

    # @flats = policy_scope(Flat)
    if params[:location].present?
      @flats = policy_scope(Flat).where("location ILIKE ?", "%#{params[:location]}%")
    else
      @flats = policy_scope(Flat)
    end

    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        image_url: 'https://res.cloudinary.com/rafxss/image/upload/v1599564146/logo_ke2eyy.png'
      }
    end

  end

  def owned
    # @flats = Flat.all
    # @flats = policy_scope(Flat)
    @owned_flats = current_user.owned_flats
    authorize @owned_flats
  end

  def booked
    # @flats = Flat.all
    # @flats = policy_scope(Flat)
    @booked_flats = current_user.booked_flats
    authorize @booked_flats
  end

  def show
    #@flat = Flat.find(params[:id])
    # Geocoder.search(casa.geocode)[0].data["address"]["city"]
    @reservation = Reservation.new
    authorize @flat

     @marker = [{
        lat: @flat.latitude,
        lng: @flat.longitude,
        image_url: 'https://res.cloudinary.com/rafxss/image/upload/v1599564146/logo_ke2eyy.png'
      }]
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create

    @flat = Flat.new(flat_params)
    @user = current_user
    @flat.user = @user
    # @flat.location = Geocoder.search(@flat.geocode)[0].data["address"]["city"]
    authorize @flat

    if @flat.save
      # redirect_to flat_path(@flat)
      redirect_to owned_flats_path
    else
      render :new
    end
  end

  def blank_stars
    5 - @flat.review.rating.to_i
    authorize @review
  end

  def edit
    # if current_user != flat.user
    #   redirect_to edit_flat_path(@flat)
    # else
    # @flat = Flat.find(params[:id])
    authorize @flat
  end

  def update
    # @flat = Flat.find(params[:id])
    # @flat.location = Geocoder.search(@flat.geocode)[0].data["address"]["city"]
    @flat.update(flat_params)
    # @flat.update(location: Geocoder.search(@flat.geocode)[0].data["address"]["city"])
    authorize @flat
    redirect_to flat_path(@flat)
  end

  def destroy
    #@flat = Flat.find(params[:id])
    @flat.destroy
    authorize @flat
    redirect_to owned_flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end


  def flat_params
    params.require(:flat).permit(:name, :description, :location, :address, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = policy_scope(Reservation).includes(:flat)

    @guest_reservations = @reservations.where(user_id: current_user.id)
    @host_reservations = @reservations.where(flats: {user_id: current_user.id})
  end

  def show
     @reservation = Reservation.find_by(id: params[:id])
     authorize @reservation
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    authorize @reservation
    if @reservation.save
      redirect_to reservations_path
    else
      redirect_to flat_path(@reservation.flat)
    end
  end


  def edit

    @reservation = Reservation.find(params[:id])
    authorize @reservation
  end

  def update
    @reservation = Reservation.where(id: params[:id])
    authorize @reservation
    @reservation.update(reservation_params)
    redirect_to reservations_path


  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to user_path(@reservation.user)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:flat_id, :user_id, :status, :reservation_start, :reservation_end)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = policy_scope(Review).all

  end
  def new
    @review = Review.new
    @flat = Flat.find(params[:flat_id])
    authorize @review
  end

  def create

    @flat = Flat.find(params[:flat_id])
    @review = Review.new(review_params)
    @review.flat_id = @flat.id
    authorize @review
    if @review.save
      redirect_to flat_path(@flat)
    else
      render :new
    end

  end

  def destroyshow
  end

  def blank_stars
    5 - @flat.review.rating.to_i
    authorize @review
  end


   private

  def review_params
    params.require(:review).permit(:description, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/booked.html.erb
<h1>Flats#Booked</h1>
<p>Find me in app/views/flats/index.html.erb</p>

<% if @booked_flats.length > 0 %>
<p>tienes booked flats</p>
<% else %>
<p>no tienes booked flats</p>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <br>
  <div class="row justify-content-center">
    <div class="col-12 col-sm-12 col-md-10 col-lg-8">
      <%= link_to "← Back", :back %>
      <div class="main shadow">

        <h2 class="text-center">Update your house</h2>
        <div class="col-12 form-group" data-controller="address">
          <%= simple_form_for(@flat) do |f| %>
              <%= f.input :name %>
              <%= f.input :description %>
              <%= f.input :address %>
              <%= f.input :price %>
              <%#<%= f.input :location, collection: [['Seville', 'Seville'], ['Madrid', 'Madrid'], ['Barcelona', 'Barcelona']], label_method: :second, value_method: :first %>
              <%= f.input :location, label: 'City'%>
              <%= f.input :photos, as: :file, input_html: { multiple: true } %>
              <%= f.button :submit, "Save", class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),url('https://res.cloudinary.com/rafxss/image/upload/v1599601770/il_1588xN.1672457821_8zt7_vlfqwf.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center;">
  <div class="container text-center text-white shadow-sm">
    <div style="padding: 75px 0px;">
      <% if params[:location]%>
        <h1 style="align-content: center; text-shadow: 2px 2px 10px #000000;">All the available dog's houses in <%= params[:location].capitalize%></h1>
      <% else %>
        <h1 style="align-content: center; text-shadow: 2px 2px 10px #000000;">All the available dog's houses</h1>
      <% end %>
      <p class="mb-3" style="text-shadow: 2px 2px 15px #000000;">Plan a different kind of getaway to uncover <br> the hidden gems near you.</p>

    </div>
  </div>
</div>

<br>

<div class="container">
    <% if current_user %>
    <div class="mb-3 mr-auto ml-auto">
      <div>
        <div class="justify-content-center">
          <%= link_to 'Create a house', new_flat_path, class: 'btn btn-pet-outline' %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="d-flex">
      <div class="col-xs-12 col-lg-6" style="padding: 15px 0px;">
      <% @flats.each do |flat| %>
      <div class="card mb-3 mr-auto ml-auto" style="border-radius: 15px;">
        <%= link_to flat_path(flat), class: "text-decoration-none color-link-none" do %>
          <div class="row no-gutters">
            <div class="col-xs-5 col-sm-4">
              <img src="<%= cl_image_path flat.photos.first.key, height: 500, width: 500, crop: :fill, class: "d-block" %>" class="card-img" alt="..." style="border-radius: 14px; object-fit: cover;">
            </div>
            <div class="col-xs-5 col-sm-8">
              <div class="card-body h-100">
                <div class="d-flex flex-column align-content-between" style="height: 100%;">
                  <div class="mb-auto">
                    <h5 class="card-title"><%= flat.name %></h5>
                    <p class="card-text maxlengthpet mb-3"><%= flat.description %></p>
                  </div>
                  <div class="d-flex justify-content-between">
                    <div class="text-muted"><i class="fas fa-map-marker-alt fa-lg mr-1" style="color:#FF5A5F"></i><span> <%= flat.location %> </span></div>
                    <div><span> <strong>  <%= flat.price %> € </strong> / day</span></div>

                     <% rate = [] %>
                    <% if flat.reviews.present? %>
                       <% flat.reviews.each do |review| %>
                          <% rate << review.rating.to_i %>
                       <% end %>
                      <% average = rate.sum / rate.count %>
                    <% else %>
                      <% average = 0 %>
                    <% end %>



                    <div><span> <strong>
                      <p >
                      <% rev = 5 - average %>
                      <% average.times do  %>
                        <i class="fas fa-paw fa-md color-pet"></i>
                      <% end %>
                      <% rev.times do  %>
                        <i class="fas fa-paw fa-md color-pet color-muted"></i>
                      <% end %>
                      </p>

                    </strong> </span></div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
      </div>
      <div class="col-xs-12 col-lg-6">
        <div data-controller="map" style="position: sticky; top: 0px; padding: 15px 0px;">
          <div id="map"
            data-target="map.map"
            style="width: 100%; height: 96.5vh; border-radius: 15px; position: sticky; top: 0px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <br>
  <div class="row justify-content-center">
    <div class="col-12 col-sm-12 col-md-10 col-lg-8">
      <%= link_to "← Back", :back %>
      <div class="main shadow">
      <h2 class="text-center">Post a new dog's house</h2>
        <div class="col-12 form-group" data-controller="address">
          <%= simple_form_for(@flat) do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :address %>
            <%= f.input :price, input_html: { min: '0' } %>
            <%# <%= f.input :location, collection: [['Seville', 'Seville'], ['Madrid', 'Madrid'], ['Barcelona', 'Barcelona']], label_method: :second, value_method: :first %>
            <%= f.input :location, label: 'City' %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>

            <input type="submit" name="commit" value="Create House" data-disable-with="Creating House" class="btn btn-primary">
          <% end %>
          <br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/owned.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),url('https://res.cloudinary.com/rafxss/image/upload/v1599601770/il_1588xN.1672457821_8zt7_vlfqwf.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center;">
  <div class="container text-center text-white shadow-sm">
    <div style="padding: 75px 0px;">
      <h1 style="align-content: center; text-shadow: 2px 2px 10px #000000;">My dog's houses</h1>

    </div>
  </div>
</div>

<br>

<div class="container">
  <div class="justify-content-center">
    <% if current_user%>
    <div class="mb-3 mr-auto ml-auto" style="max-width: 600px;">
      <div>
        <div class="justify-content-center">
          <%= link_to 'Create a house', new_flat_path, class: 'btn btn-pet-outline' %>
        </div>
      </div>
    </div>
    <% end %>
  <% if @owned_flats.empty? %>
    <h1 class="text-center"style="align-content: center;">You dont own any flats 😅</h1>
  <% else %>
  <div class="justify-content-center">
    <% @owned_flats.each do |flat| %>
    <div class="card mb-3 mr-auto ml-auto" style="max-width: 600px; border-radius: 15px;">
      <%= link_to flat_path(flat), class: "text-decoration-none color-link-none" do %>
        <div class="row no-gutters">
          <div class="col-xs-5 col-md-4">
            <img src="<%= cl_image_path flat.photos.first.key, height: 500, width: 500, crop: :fill, class: "d-block" %>" class="card-img" alt="..." style="border-radius: 14px; object-fit: cover;">
          </div>
          <div class="col-xs-7 col-md-8">
            <div class="card-body h-100">
              <div class="d-flex flex-column align-content-between" style="height: 100%;">
                <div class="mb-auto">
                  <h5 class="card-title"><%= flat.name %></h5>
                  <p class="card-text maxlengthpet mb-3"><%= flat.description %></p>
                </div>
                <div class="d-flex justify-content-between">
                  <div class="text-muted"><i class="fas fa-map-marker-alt fa-lg mr-1" style="color:#FF5A5F"></i><span> <%= flat.location %> </span></div>
                  <div><span> <strong>  <%= flat.price %> € </strong> / day</span></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
<% end %>
</div>
</div>

app/views/flats/show.html.erb
<div class="show">
  <div class="container">
    <div class="d-flex align-items-center mt-4">
      <div><h3 class="m-0"><strong> <%= @flat.name.capitalize %> </strong></h3></div>
      <% if current_user == @flat.user %>
          <div><a class="btn btn-sm btn-pet-outline ml-3" href="/flats/<%= @flat.id %>/edit">Edit<i class="fas fa-edit ml-2"></i></a></div>
          <div><a data-confirm="Are you sure?" class="btn btn-sm btn-pet-outline ml-2" rel="nofollow" data-method="delete" href="/flats/<%= @flat.id %>">Delete<i class="fas fa-trash-alt ml-2"></i></a></div>
      <% end %>
    </div>
    <div class="text-muted mt-2"><i class="fas fa-map-marker-alt fa-lg mr-1" style="color:#FF5A5F"></i><span> <%= @flat.location %> </span></div>
    <br>
    <div id="carouselExampleIndicators" class="carousel slide mt-2" data-ride="carousel" style='height:200;'>
        <div class="carousel-inner" style="border-radius: 15px;" >
          <% @flat.photos.each_with_index do |flat, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <img class="d-block w-100" src="<%= cl_image_path flat.key, aspect_ratio: 3.2, quality: 100, crop: :fill, gravity: :center, class: "d-block" %>" alt="First slide">
            </div>
          <% end %>
        </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
    </div>
  </div>
  <br>
  <div class="container">

    <div>
      <div class="row justify-content-between">
      <div class="col-xs-12 col-lg-8">
        <div class="product-box shadow">
          <h5 class="mb-3"><i class="fas fa-home mr-1 color-pet"></i> Flat Description</h5>
          <p><%= @flat.description %></p>
        </div>
        <div class="product-box shadow">
          <h5 class="mb-3"><i class="fas fa-map-marked-alt mr-1 color-pet"></i> Flat Address</h5>
            <p><%= @flat.address%></p>
        </div>

         <div class="product-box shadow">
          <h5 class="mb-3"> <i class="far fa-id-badge mr-2 color-pet"></i>Flat Reviews (<%= link_to "Add review", new_flat_review_path(@flat) %>)   </h5>
          <span class="glyphicon glyphicon-star" aria-hidden="true"></span>

            <% @flat.reviews.each do |review| %>
                <% rev = 5 - review.rating.to_i %>


                <span><strong><p >
                <%= review.description%>
                <% review.rating.times do  %>
                  <i class="fas fa-paw fa-md color-pet"></i>
                <% end %>
                <% rev.times do  %>
                  <i class="fas fa-paw fa-md color-pet color-muted"></i>
                <% end %>
                </p></strong></span>


            <% end %>
        </div>

      </div>
      <div class="book-form col-xs-12 col-lg-4">
            <% if current_user != @flat.user %>
          <div class="dates product-box shadow">
          <div class="form-group row">
            <div style="padding-top: 0; padding-left: 15px; width:96.5%;">
             <%= simple_form_for(@reservation) do |f| %>
              <div class="d-flex justify-content-between align-items-center mb-4">
                <div><h5 class="m-0"><i class="far fa-calendar-alt mr-1 color-pet"></i> Select a date</h5></div>
                <div><h4 style="opacity: 1;" class="m-0"><strong><%=@flat.price %> €</strong> / day</h4></div>
              </div>
              <%= f.input :reservation_start, as: :string, required: true, autofocus: true, input_html: {type: :date} %>
              <%= f.input :reservation_end, as: :string, required: true, autofocus: true, input_html: {type: :date} %>
              <%= f.hidden_field :flat_id, value: @flat.id %>
              <div class="d-flex flex-row-reverse">
                <%= f.button :submit, "Book", class: 'btn btn-pet w-100' %>
                <!-- <div><input type="submit" name="commit" value="Book" data-disable-with="Booking" class="btn btn-pet px-4"></div> -->
              </div>
            </div>
          </div>
          </div>
            <% end %>
          <% end %>
        <div>
          <div data-controller="map">
            <div id="map"
              data-target="map.map"
              style="width: 100%; min-height: 350px; border-radius: 15px; margin-top: 20px;"
              data-markers="<%= @marker.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag 'https://res.cloudinary.com/rafxss/image/upload/v1599564146/logo_ke2eyy.png' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <main><%= yield %></main>

    <%= render 'shared/footer' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <% flash.each do |type, msg| %>
    <div class="alert alert-pet alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close text-white" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

<div style="background-image: url('https://res.cloudinary.com/rafxss/image/upload/v1599566629/landing_oqzaqu.png'); background-repeat: no-repeat; background-size: cover; background-position: right top;">
  <div class="container">
    <div style="padding: 150px 100px 150px;">
      <h1 style="align-content: center;">Welcome to Petbnb</h1>
      <p class="mb-3">Plan a different kind of getaway to uncover <br> the hidden gems near you.</p>
      <a href="/flats" class="btn my-2 my-sm-0 btn-pet">Discover</a>
      <a href="/flats/new" class="btn my-2 my-sm-0 btn-pet-outline">Post a dog's house</a>

    </div>
  </div>
</div>
<div class="container">
  <h2 class="mt-5 mb-5 text-center">🐶 Discover our places! 🐶</h2>
   <div class="row">
      <div class="col-6 col-sm-6 col-md-4 col-lg-4 p-3">
        <a href="/flats?location=seville">
        <div class="card text-white" style="background-color: black; border: 0; border-radius: 15px;">
          <img class="card-img" src="https://source.unsplash.com/1200x900/?seville" style="border-radius: 15px; opacity: 0.6;" alt="Card image">
          <div class="card-img-overlay d-flex align-items-center justify-content-center">
            <h3 class="card-title m-0">Seville</h3>
          </div>
        </div>
        </a>
      </div>
      <div class="col-6 col-sm-6 col-md-4 col-lg-4 p-3">
        <a href="/flats?location=barcelona">
        <div class="card text-white" style="background-color: black; border: 0; border-radius: 15px;">
          <img class="card-img" src="https://source.unsplash.com/1200x900/?barcelona" style="border-radius: 15px; opacity: 0.6;" alt="Card image">
          <div class="card-img-overlay d-flex align-items-center justify-content-center">
            <h3 class="card-title m-0">Barcelona</h3>
          </div>
        </div>
        </a>
      </div>
      <div class="col-6 col-sm-6 col-md-4 col-lg-4 p-3">
        <a href="/flats?location=madrid">
        <div class="card text-white" style="background-color: black; border: 0; border-radius: 15px;">
          <img class="card-img" src="https://source.unsplash.com/1200x900/?madrid" style="border-radius: 15px; opacity: 0.6;" alt="Card image">
          <div class="card-img-overlay d-flex align-items-center justify-content-center">
            <h3 class="card-title m-0">Madrid</h3>
          </div>
        </div>
        </a>
      </div>
    </div>
</div>

app/views/reservations/edit.html.erb
<div class="container">
  <br>
  <div class="row justify-content-center">
    <div class="col-12 col-sm-12 col-md-10 col-lg-8">
      <%= link_to "← Back", :back %>
      <div class="main shadow">

        <h2 class="text-center">Edit</h2>
        <div class="col-12 form-group">
          <% if current_user != @reservation.flat.user %>
            <%= simple_form_for(@reservation) do |f| %>
                <%= f.label "Start Date" %>
                <%= f.input :reservation_start %>
                <%= f.label "End Date" %>
                <%= f.input :reservation_end %>
                <%= f.hidden_field :flat_id, value: @reservation.flat_id %>
              <div><p style="opacity: 1;"><strong><%=@reservation.flat.price%> €</strong> / day</p></div>
              <input type="submit" name="commit" value="Create reservation" data-disable-with="Create reservation" class="btn btn-primary">
              <% end %>
            <% end %>


            <% if current_user == @reservation.flat.user %>
              <% if @reservation.status != "approved" || "rejected" %>
                <%= simple_form_for(@reservation) do |f| %>
                  <%= f.hidden_field :flat_id, value: @reservation.flat_id %>
                  <%= f.hidden_field :status, value: "approved" %>
                  <%= f.button :submit, "Approve", class: 'btn btn-success' %>
                <% end %>

                <%= simple_form_for(@reservation) do |f| %>
                  <%= f.hidden_field :flat_id, value: @reservation.flat_id %>
                  <%= f.hidden_field :status, value: "rejected" %>
                  <%= f.button :submit, "Reject", class: 'btn btn-danger' %>
                <% end %>
                <% else %>
                  <%= @reservation.status %>

              <% end %>

            <% end %>




        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroyshow.html.erb
<h1>Reviews#destroyshow</h1>
<p>Find me in app/views/reviews/destroyshow.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <br>
  <div class="row justify-content-center">
    <div class="col-12 col-sm-12 col-md-10 col-lg-8">
      <%= link_to "← Back", :back %>
      <div class="main shadow">

        <h2 class="text-center">Create a review</h2>
        <div class="col-12 form-group">

          <%= simple_form_for([@flat, @review]) do |f| %>

            <div class="form-inputs">
                <%= f.input :description %>
                <%= f.input :rating %>
                <%= f.hidden_field :flat_id, value: @review.flat_id %>
            </div>
            <div class="d-flex justify-content-between">
              <div class="form-actions w-100">
                <%= f.button :submit, "Create a review", class: 'btn btn-primary w-100' %>
              </div>
            </div>
          <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small card-footer">
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Petbnb</a>
  </div>
</footer>